CONFIG = {
    "data_path": "/home/ubuntu/Shosyn-1.0/dataset/enriched_simulation_logs_500_new.csv",
    "processed_data_path": "processed_cde_data.pt",
    "batch_size": 64,
    "learning_rate": 1e-4,
    "weight_decay": 1e-5,
    "epochs": 50,
    "hidden_channels": 64,
    "cde_func_channels": 128,
    "cde_func_depth": 3,
    "readout_hidden_channels": 64,
    "num_workers": 4,
    "clip_value": 1.0,
    "scheduler_patience": 3,
    "scheduler_factor": 0.1,
}
